alias v = nvim
alias yy = y
alias tf = terraform
alias ap = ansible-playbook
alias dc = docker compose
alias gs = git status
alias gd = git diff
alias gco = git checkout
alias gst = git stash
alias cat = bat
